### PR TITLE
Style/page/match search

### PR DESCRIPTION
**Pull request by ahn0min**
#### 전적 검색 결과 페이지
1. 해당 경기의 포메이션 작업
2. 현재까지 불러온 경기 결과의 승률
3. 현재까지 불러온 경기 결과의 가장 많은 MVP 선수 이미지

### CODE REVIEW

**Comment by jungbyungwook** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>628fdaa</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://fiondb-ridcs2llb-jungbyungwook.vercel.app'>https://fiondb-ridcs2llb-jungbyungwook.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/jungbyungwook/fiondb/2he9Zq1XZWUqBVH3Px1TwvfQRwfH'>https://vercel.com/jungbyungwook/fiondb/2he9Zq1XZWUqBVH3Px1TwvfQRwfH</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/jungbyungwook/FIONDB/actions/runs/3883815867)

**Comment by jungbyungwook** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>ec91408</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://fiondb-6r8sb43f4-jungbyungwook.vercel.app'>https://fiondb-6r8sb43f4-jungbyungwook.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/jungbyungwook/fiondb/9UpV6yCWmmUpRmKBR3mZ3gnGdcbc'>https://vercel.com/jungbyungwook/fiondb/9UpV6yCWmmUpRmKBR3mZ3gnGdcbc</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/jungbyungwook/FIONDB/actions/runs/3888922140)

**Comment by jungbyungwook** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>a6b036c</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://fiondb-ncvtcco4r-jungbyungwook.vercel.app'>https://fiondb-ncvtcco4r-jungbyungwook.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/jungbyungwook/fiondb/EdKxWKKHo11CSuCmSt3xSV5Z9SRQ'>https://vercel.com/jungbyungwook/fiondb/EdKxWKKHo11CSuCmSt3xSV5Z9SRQ</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/jungbyungwook/FIONDB/actions/runs/3902660320)

**Comment by jungbyungwook** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>145defc</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://fiondb-9ygy9zu3u-jungbyungwook.vercel.app'>https://fiondb-9ygy9zu3u-jungbyungwook.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/jungbyungwook/fiondb/EKQobKiNmqS3d7TnAprzBfbsAsrS'>https://vercel.com/jungbyungwook/fiondb/EKQobKiNmqS3d7TnAprzBfbsAsrS</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/jungbyungwook/FIONDB/actions/runs/3919295443)

**Review by jungbyungwook — APPROVED** [review]
고생하셨습니다~ 애니메이션도 넣으셨내요! 굿입니다

**Comment by ahn0min** [comment]
ㅋㅋㅋ 간단히 연습삼아 넘어봤습니다

**Review by ghost — APPROVED** [review]
영민님 고생많으셨어요~  애니메이션 재밌네요

**Pull request merged**
